

#1**Trigger** – Runs on every push to the `main` branch.
#2. **Checkout** – Pulls your repo code into the runner.
#3. **Docker Login** – Authenticates to Docker Hub using secrets.
#4. **Build** – Builds the Docker image as `sagarmagar0709/myapp:latest`.
#5. **Push** – Pushes the image to Docker Hub.

name: Build, Push, and Update Deployment YAML

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Docker Image Tag
        id: vars
        run: echo "TAG=latest-$(date +%s)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t sagarmagar0709/myapp:${{ env.TAG }} .

      - name: Push Docker Image
        run: docker push sagarmagar0709/myapp:${{ env.TAG }}

      - name: Update deployment.yaml with new image
        run: |
          sed -i 's|image: sagarmagar0709/myapp:.*|image: sagarmagar0709/myapp:${{ env.TAG }}|' k8s/deployment.yaml

      - name: Commit updated deployment.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add k8s/deployment.yaml
          git commit -m "Update image tag to ${{ env.TAG }}"
          git push
