name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # or any other branch you prefer

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t sagarmagar0709/myapp:latest .

      - name: Push Docker image to Docker Hub
        run: docker push sagarmagar0709/myapp:latest
