

#1**Trigger** – Runs on every push to the `main` branch.
#2. **Checkout** – Pulls your repo code into the runner.
#3. **Docker Login** – Authenticates to Docker Hub using secrets.
#4. **Build** – Builds the Docker image as `sagarmagar0709/myapp:latest`.
#5. **Push** – Pushes the image to Docker Hub.

name: Build and Update Deployment YAML

on:
  push:
    branches:
      - main

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t sagarmagar0709/myapp:latest .

      - name: Push Docker image to Docker Hub
        run: docker push sagarmagar0709/myapp:latest

      - name: Update image in deployment.yaml
        run: |
          sed -i 's|^\s*image:.*|          image: sagarmagar0709/myapp:latest|' k8s/deployment.yaml
          cat k8s/deployment.yaml

      - name: Commit and push updated deployment.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add k8s/deployment.yaml
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "chore: update image tag to latest"
          git push || echo "Nothing to push"
