

#1**Trigger** – Runs on every push to the `main` branch.
#2. **Checkout** – Pulls your repo code into the runner.
#3. **Docker Login** – Authenticates to Docker Hub using secrets.
#4. **Build** – Builds the Docker image as `sagarmagar0709/myapp:latest`.
#5. **Push** – Pushes the image to Docker Hub.

name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t sagarmagar0709/myapp:latest .

      - name: Push Docker Image
        run: docker push sagarmagar0709/myapp:latest
