

#1**Trigger** – Runs on every push to the `main` branch.
#2. **Checkout** – Pulls your repo code into the runner.
#3. **Docker Login** – Authenticates to Docker Hub using secrets.
#4. **Build** – Builds the Docker image as `sagarmagar0709/myapp:latest`.
#5. **Push** – Pushes the image to Docker Hub.
#6 Deployment

name: Build, Push, and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set Docker Image Tag
        id: vars
        run: echo "TAG=latest-$(date +%s)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t sagarmagar0709/myapp:${{ env.TAG }} .

      - name: Push Docker Image
        run: docker push sagarmagar0709/myapp:${{ env.TAG }}

      - name: Update deployment.yaml with new image
        run: |
          sed -i 's|image: sagarmagar0709/myapp:.*|image: sagarmagar0709/myapp:${{ env.TAG }}|' deployment.yml

      - name: Commit updated deployment.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add deployment.yml
          git commit -m "Update image tag to ${{ env.TAG }}"
          git push

      # --- EKS Deployment Section Starts Here ---
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # change to your region

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --region us-east-1 --name dev-cluster

      - name: Deploy to EKS
        run: kubectl apply -f deployment.yml
